//
//  SurveyLibraryLiteral.h
//  nankang
//
//  Created by 军锋 安 on 12-7-17.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>
@interface SurveyLibraryLiteral : NSObject
{
    NSString* MessCannotSetValue;
	NSString* MessIllegalBoolValue;
	NSString* MessIllegalProperty;
	NSString* MessNotSupportOperate;
	NSString* MessPropertyCannotSetValue;
	NSString* MessScriptCannotResolved;
    
	NSString* MessCannotFindQuestionnaire;
	NSString* MessQuotaVOEmpty;
    
	NSString* MessInvalidParameter;
	NSString* MessSelectedOpenOptionEmpty;
    
	int IdLength;
	NSString* AnswerVSplit;
	NSString* AnswerCSplit;
	NSString* ScriptStatementSplit;
	NSString* QuestionFlowSplit;
	NSString* AnswerVariableFlowSplit;
	NSString* AnswerContentQInfoElementIdSplit;
	NSString* ScriptTextDelimiter;
	NSString* MixQuestionOptionDelimiter;
    
	int DisplayEffectHide;
	int DisplayEffectDisable;
	int DisplayEffectHighlight;
    
	int ScriptGet;
	int ScriptSet;
    
	NSArray* MapSurveyXMLElement;
	int SurveyXMLElement_Library;
	int SurveyXMLElement_Category;
	int SurveyXMLElement_Survey;
	int SurveyXMLElement_SurveyMedia;
	int SurveyXMLElement_WelcomeSentence;
	int SurveyXMLElement_QuitSentence;
	int SurveyXMLElement_Variable;
	int SurveyXMLElement_OptionList;
	int SurveyXMLElement_OptionListItem;
	int SurveyXMLElement_CategoryList;
	int SurveyXMLElement_CategoryListItem;
	int SurveyXMLElement_SubSurvey;
	int SurveyXMLElement_Section;
	int SurveyXMLElement_GreetingQuestion;
	int SurveyXMLElement_ScriptQuestion;
	int SurveyXMLElement_SBlankQuestion;
	int SurveyXMLElement_MBlankQuestion;
	int SurveyXMLElement_SChoiceQuestion;
	int SurveyXMLElement_MChoiceQuestion;
	int SurveyXMLElement_MChoiceOrderQuestion;
	int SurveyXMLElement_ThreeBFormQuestion;
	int SurveyXMLElement_MixMChoiceQuestion;
	int SurveyXMLElement_BFormQuestion;
	int SurveyXMLElement_SFormQuestion;
	int SurveyXMLElement_MFormQuestion;
	int SurveyXMLElement_SequenceQuestion;
	int SurveyXMLElement_ThreeSFormQuestion;
	int SurveyXMLElement_ThreeMFormQuestion;
	int SurveyXMLElement_QuestionExpression;
	int SurveyXMLElement_InitExpression;
	int SurveyXMLElement_CheckExpression;
	int SurveyXMLElement_OperateExpression;
	int SurveyXMLElement_GotoExpression;
	int SurveyXMLElement_ComputeBeforeValidExpression;
	int SurveyXMLElement_PlaybackId;
	int SurveyXMLElement_QuestionHead;
	int SurveyXMLElement_QItem;
	int SurveyXMLElement_QItemMedia;
	int SurveyXMLElement_QItemPhoto;
	int SurveyXMLElement_QItemMediaRecord;
	int SurveyXMLElement_AItem;
	int SurveyXMLElement_AItemMedia;
    int SurveyXMLElement_AItemPhoto;
    int SurveyXMLElement_CItemPhoto;
	int SurveyXMLElement_CItem;
	int SurveyXMLElement_CItemMedia;
	int SurveyXMLElement_QuestionMedia;
	int SurveyXMLElement_QuestionFileMedia;
	int SurveyXMLElement_QuestionBackgroundMedia;
	int SurveyXMLElement_QuestionPhoto;
	int SurveyXMLElement_QuestionMediaRecord;
	int SurveyXMLElement_QuestionMapMedia;
	int SurveyXMLElement_MapNode;
    
	NSArray* MapSurveyXMLAttrib;
	int SurveyXMLAttrib_Id;
	int SurveyXMLAttrib_Identity;
	int SurveyXMLAttrib_SurveyName;
	int SurveyXMLAttrib_SurveyCode;
	int SurveyXMLAttrib_Creator;
    
	int SurveyXMLAttrib_Modifier;
	int SurveyXMLAttrib_CreateDate;
	int SurveyXMLAttrib_ModifyDate;
	int SurveyXMLAttrib_Status;
	int SurveyXMLAttrib_Memo;
	int SurveyXMLAttrib_NeedRecord;
	int SurveyXMLAttrib_DenyEmptyAnswer;
	int SurveyXMLAttrib_ChoiceDefaultCols;
	int SurveyXMLAttrib_ShowPercentRule;
	int SurveyXMLAttrib_HideWelcomeSentence;
	int SurveyXMLAttrib_HidePrevButton;
	int SurveyXMLAttrib_QuestionNoShowMode;
	int SurveyXMLAttrib_ItemNoShowMode;
	int SurveyXMLAttrib_SubSurveyAlternation;
	int SurveyXMLAttrib_SubSurveyDraw;
	int SurveyXMLAttrib_TitleFontFamily;
	int SurveyXMLAttrib_TitleFontSize;
	int SurveyXMLAttrib_TitleFontStyle;
	int SurveyXMLAttrib_TipFontFamily;
	int SurveyXMLAttrib_TipFontSize;
	int SurveyXMLAttrib_TipFontStyle;
	int SurveyXMLAttrib_ItemFontFamily;
	int SurveyXMLAttrib_ItemFontSize;
	int SurveyXMLAttrib_ItemFontStyle;
	int SurveyXMLAttrib_WelcomeFontFamily;
	int SurveyXMLAttrib_WelcomeFontSize;
	int SurveyXMLAttrib_WelcomeFontStyle;
	int SurveyXMLAttrib_QuitFontFamily;
	int SurveyXMLAttrib_QuitFontSize;
	int SurveyXMLAttrib_QuitFontStyle;
	int SurveyXMLAttrib_DefaultTitleForeColor;
	int SurveyXMLAttrib_DefaultTipForeColor;
	int SurveyXMLAttrib_DefaultItemForeColor;
	int SurveyXMLAttrib_WelcomeColor;
	int SurveyXMLAttrib_QuitColor;
	int SurveyXMLAttrib_SurveyGpsPolicy;
	int SurveyXMLAttrib_Version;
    
	NSArray* MapSubSurveyXMLAttrib;
	int SubSurveyXMLAttrib_Id;
	int SubSurveyXMLAttrib_Identity;
	int SubSurveyXMLAttrib_Name;
	int SubSurveyXMLAttrib_IsAlternation;
	int SubSurveyXMLAttrib_IsDraw;
	int SubSurveyXMLAttrib_Memo;
	int SubSurveyXMLAttrib_IsSamePage;
	int SubSurveyXMLAttrib_SectionAlternation;
	int SubSurveyXMLAttrib_SectionDraw;
    
	NSArray* MapSectionXMLAttrib;
	int SectionXMLAttrib_Id;
	int SectionXMLAttrib_Identity;
	int SectionXMLAttrib_Name;
	int SectionXMLAttrib_IsAlternation;
	int SectionXMLAttrib_IsDraw;
	int SectionXMLAttrib_Memo;
	int SectionXMLAttrib_IsSamePage;
	int SectionXMLAttrib_QuestionAlternation;
	int SectionXMLAttrib_QuestionDraw;
    
	NSArray* MapQuestionXMLAttrib;
	int QuestionXMLAttrib_Id;
	int QuestionXMLAttrib_Identity;
	int QuestionXMLAttrib_Title;
	int QuestionXMLAttrib_Code;
	int QuestionXMLAttrib_Tip;
	int QuestionXMLAttrib_IsAlternation;
	int QuestionXMLAttrib_IsDraw;
	int QuestionXMLAttrib_Memo;
	int QuestionXMLAttrib_IsSamePage;
	int QuestionXMLAttrib_IsDumb;
	int QuestionXMLAttrib_IsQuota;
	int QuestionXMLAttrib_QuotaFailedExpression;
	int QuestionXMLAttrib_FontFamily;
	int QuestionXMLAttrib_FontSize;
	int QuestionXMLAttrib_FontStyle;
	int QuestionXMLAttrib_ForeColor;
	int QuestionXMLAttrib_TipFontFamily;
	int QuestionXMLAttrib_TipFontSize;
	int QuestionXMLAttrib_TipFontStyle;
	int QuestionXMLAttrib_TipForeColor;
	int QuestionXMLAttrib_Style;
	int QuestionXMLAttrib_MinItemAnswer;
	int QuestionXMLAttrib_MaxItemAnswer;
	int QuestionXMLAttrib_ItemAlternation;
	int QuestionXMLAttrib_ItemDraw;
	int QuestionXMLAttrib_OptionListId;
	int QuestionXMLAttrib_CategoryListId;
	int QuestionXMLAttrib_ItemLayout;
	int QuestionXMLAttrib_TableOddRowBColorSet;
	int QuestionXMLAttrib_TableEvenRowBColorSet;
	int QuestionXMLAttrib_TableOddColBColorSet;
	int QuestionXMLAttrib_TableEvenColBColorSet;
	int QuestionXMLAttrib_TableOddRowBColor;
	int QuestionXMLAttrib_TableEvenRowBColor;
	int QuestionXMLAttrib_TableOddColBColor;
	int QuestionXMLAttrib_TableEvenColBColor;
	int QuestionXMLAttrib_AItemAlternation;
	int QuestionXMLAttrib_CItemAlternation;
	int QuestionXMLAttrib_CItemDraw;
	int QuestionXMLAttrib_AnswerTimeLimitMode;
	int QuestionXMLAttrib_AnswerTimeLimit;
	int QuestionXMLAttrib_NeedRecord;
	int QuestionXMLAttrib_IgnoreLastAnswer;
	int QuestionXMLAttrib_DenyEmptyAnswer;
	int QuestionXMLAttrib_CanSkip;
	int QuestionXMLAttrib_CItemIndexHide;
	int QuestionXMLAttrib_QItemIndexHide;
	int QuestionXMLAttrib_AItemIndexHide;
	int QuestionXMLAttrib_OptionDisplayOrder;
	int QuestionXMLAttrib_OptionDisplayStyle;
	int QuestionXMLAttrib_ScaleStyle;
	int QuestionXMLAttrib_MinScaleText;
	int QuestionXMLAttrib_MaxScaleText;
	int QuestionXMLAttrib_CItemImageStyleSetting;
	int QuestionXMLAttrib_QItemImageStyleSetting;
	int QuestionXMLAttrib_AItemImageStyleSetting;
	int QuestionXMLAttrib_QuestionShowItemNo;
	int QuestionXMLAttrib_ItemColNums;
	int QuestionXMLAttrib_ItemColWidth;
	int QuestionXMLAttrib_ItemColSpace;
	int QuestionXMLAttrib_ItemRowSpace;
	int QuestionXMLAttrib_ShowItemTitleInRule;
	int QuestionXMLAttrib_QHeadMarginLeft;
	int QuestionXMLAttrib_QHeadMarginRight;
	int QuestionXMLAttrib_QHeadMarginTop;
	int QuestionXMLAttrib_QHeadMarginBottom;
	int QuestionXMLAttrib_QHeadSpaceBetweenTitleTip;
	int QuestionXMLAttrib_QHeadSpaceBetweenTitleMedia;
	int QuestionXMLAttrib_QHeadMediaTitlePos;
	int QuestionXMLAttrib_QHeadTitleTipPos;
	int QuestionXMLAttrib_QHeadTitleAlign;
	int QuestionXMLAttrib_QHeadTipAlign;
	int QuestionXMLAttrib_QHeadMediaAlign;
	int QuestionXMLAttrib_QHeadTitleWidth;
	int QuestionXMLAttrib_QHeadTipWidth;
	int QuestionXMLAttrib_TableRowWidth;
	int QuestionXMLAttrib_TableCItemRowWidth;
	int QuestionXMLAttrib_QuestionPhotoPolicy;
	int QuestionXMLAttrib_QuestionMediaRecordPolicy;
	int QuestionXMLAttrib_GpsPolicy;
	int QuestionXMLAttrib_TitleHasScript;
	int QuestionXMLAttrib_TipHasScript;
	int QuestionXMLAttrib_ItemTitleHasScript;
    
	NSArray* MapItemXMLAttrib;
	int ItemXMLAttrib_Id;
	int ItemXMLAttrib_Identity;
	int ItemXMLAttrib_Title;
	int ItemXMLAttrib_Code;
	int ItemXMLAttrib_Category;
	int ItemXMLAttrib_Index;
	int ItemXMLAttrib_IsAlternation;
	int ItemXMLAttrib_IsDraw;
	int ItemXMLAttrib_IsOpen;
	int ItemXMLAttrib_IsHold;
	int ItemXMLAttrib_Prop;
	int ItemXMLAttrib_Min;
	int ItemXMLAttrib_Max;
	int ItemXMLAttrib_MaxNumOperator;
	int ItemXMLAttrib_MinNumOperator;
	int ItemXMLAttrib_OpenTextShowAsPwd;
	int ItemXMLAttrib_Memo;
	int ItemXMLAttrib_FontFamily;
	int ItemXMLAttrib_FontSize;
	int ItemXMLAttrib_FontStyle;
	int ItemXMLAttrib_ForeColor;
	int ItemXMLAttrib_OptionListItemId;
	int ItemXMLAttrib_CategoryListItemId;
	int ItemXMLAttrib_WithKnowledge;
	int ItemXMLAttrib_ImageTextShowMode;
	int ItemXMLAttrib_ImageTextPos;
	int ItemXMLAttrib_MarkEndTime;
	int ItemXMLAttrib_IsOpenTextShowByDigit;
	int ItemXMLAttrib_OpenTextFractionNum;
	int ItemXMLAttrib_OpenTextPrefix;
	int ItemXMLAttrib_OpenTextPostfix;
	int ItemXMLAttrib_ItemColWidth;
	int ItemXMLAttrib_TitleHasScript;
    
	NSArray* MapMediaXMLAttrib;
	int MediaXMLAttrib_Id;
	int MediaXMLAttrib_Title;
	int MediaXMLAttrib_Index;
	int MediaXMLAttrib_MediaCategory;
	int MediaXMLAttrib_MediaFormat;
	int MediaXMLAttrib_SizeMode;
	int MediaXMLAttrib_Width;
	int MediaXMLAttrib_Height;
	int MediaXMLAttrib_DisplayMode;
	int MediaXMLAttrib_FilePath;
	int MediaXMLAttrib_WebFilePath;
	int MediaXMLAttrib_Memo;
	int MediaXMLAttrib_FillColor;
    
	NSArray* MapMapNodeXMLAttrib;
	int MapNodeXMLAttrib_Id;
	int MapNodeXMLAttrib_Index;
	int MapNodeXMLAttrib_ItemId;
	int MapNodeXMLAttrib_ShapeType;
	int MapNodeXMLAttrib_PointStr;
	int MapNodeXMLAttrib_Title;
    //欢迎语 结束语
    NSArray* MapSentenceXMLAttrib;
    int MapSentenceXMLAttrib_Id;
    int MapSentenceXMLAttrib_Identity;
    int MapSentenceXMLAttrib_Title;
    int MapSentenceXMLAttrib_Expression;
    
    //问卷变量
    NSArray* MapVariablesXMLAttrib;
    int MapVariablesXMLAttrib_Id;
    int MapVariablesXMLAttrib_Name;
    int MapVariablesXMLAttrib_Type;
    
    //选项列表
    NSArray* MapListsXMLAttrib;
    int MapListsXMLAttrib_Id;
    int MapListsXMLAttrib_Index;
    int MapListsXMLAttrib_Name;
    int SurveyXMLElement_QuitSentences;
    int SurveyXMLElement_Variables;
    int SurveyXMLElement_SubSurveys;
    int SurveyXMLElement_Sections;
    int SurveyXMLElement_Questions;
    int SurveyXMLElement_QItems;
    int SurveyXMLElement_QuestionMapNodes;
    int SurveyXMLElement_AItems;
    int SurveyXMLElement_CItems;
    int SurveyXMLElement_QuestionExpressions; 
    int SurveyXMLElement_InitExpressions; 
    int SurveyXMLElement_CheckExpressions;
    int SurveyXMLElement_OperateExpressions; 
    int SurveyXMLElement_GotoExpressions; 
    int SurveyXMLElement_ComputebeforevalidExpressions;
}
@property(nonatomic,assign)int SurveyXMLElement_AItemPhoto;
@property(nonatomic,assign)int SurveyXMLElement_CItemPhoto;
@property(nonatomic,assign)int SurveyXMLElement_QuestionExpressions; 
@property(nonatomic,assign)int SurveyXMLElement_InitExpressions; 
@property(nonatomic,assign)int SurveyXMLElement_CheckExpressions;
@property(nonatomic,assign)int SurveyXMLElement_OperateExpressions; 
@property(nonatomic,assign)int SurveyXMLElement_GotoExpressions; 
@property(nonatomic,assign)int SurveyXMLElement_ComputebeforevalidExpressions;
@property(nonatomic,assign)int SurveyXMLElement_CItems;
@property(nonatomic,assign)int SurveyXMLElement_AItems;
@property(nonatomic,assign)int SurveyXMLElement_QuestionMapNodes;
@property(nonatomic,assign)int SurveyXMLElement_QItems;
@property(nonatomic,assign)int SurveyXMLElement_Questions;
@property(nonatomic,assign)int SurveyXMLElement_Sections;
@property(nonatomic,assign)int SurveyXMLElement_SubSurveys;
@property(nonatomic,assign) int       SurveyXMLElement_Variables;
@property(nonatomic,assign) int       SurveyXMLElement_QuitSentences;
@property(strong,nonatomic) NSString* MessCannotSetValue;
@property(strong,nonatomic) NSString* MessIllegalBoolValue;
@property(strong,nonatomic) NSString* MessIllegalProperty;
@property(strong,nonatomic) NSString* MessNotSupportOperate;
@property(strong,nonatomic) NSString* MessPropertyCannotSetValue;
@property(strong,nonatomic) NSString* MessScriptCannotResolved;

@property(strong,nonatomic) NSString* MessCannotFindQuestionnaire;
@property(strong,nonatomic) NSString* MessQuotaVOEmpty;

@property(strong,nonatomic) NSString* MessInvalidParameter;
@property(strong,nonatomic) NSString* MessSelectedOpenOptionEmpty;

@property(nonatomic,assign) int IdLength;
@property(strong,nonatomic) NSString* AnswerVSplit;
@property(strong,nonatomic) NSString* AnswerCSplit;
@property(strong,nonatomic) NSString* ScriptStatementSplit;
@property(strong,nonatomic) NSString* QuestionFlowSplit;
@property(strong,nonatomic) NSString* AnswerVariableFlowSplit;
@property(strong,nonatomic) NSString* AnswerContentQInfoElementIdSplit;
@property(strong,nonatomic) NSString* ScriptTextDelimiter;
@property(strong,nonatomic) NSString* MixQuestionOptionDelimiter;

@property(nonatomic,assign) int DisplayEffectHide;
@property(nonatomic,assign) int DisplayEffectDisable;
@property(nonatomic,assign) int DisplayEffectHighlight;

@property(nonatomic,assign) int ScriptGet;
@property(nonatomic,assign) int ScriptSet;

@property(strong,nonatomic) NSArray* MapSurveyXMLElement;
@property(nonatomic,assign) int SurveyXMLElement_Library;
@property(nonatomic,assign) int SurveyXMLElement_Category;
@property(nonatomic,assign) int SurveyXMLElement_Survey;
@property(nonatomic,assign) int SurveyXMLElement_SurveyMedia;
@property(nonatomic,assign) int SurveyXMLElement_WelcomeSentence;
@property(nonatomic,assign) int SurveyXMLElement_QuitSentence;
@property(nonatomic,assign) int SurveyXMLElement_Variable;
@property(nonatomic,assign) int SurveyXMLElement_OptionList;
@property(nonatomic,assign) int SurveyXMLElement_OptionListItem;
@property(nonatomic,assign) int SurveyXMLElement_CategoryList;
@property(nonatomic,assign) int SurveyXMLElement_CategoryListItem;
@property(nonatomic,assign) int SurveyXMLElement_SubSurvey;
@property(nonatomic,assign) int SurveyXMLElement_Section;
@property(nonatomic,assign) int SurveyXMLElement_GreetingQuestion;
@property(nonatomic,assign) int SurveyXMLElement_ScriptQuestion;
@property(nonatomic,assign) int SurveyXMLElement_SBlankQuestion;
@property(nonatomic,assign) int SurveyXMLElement_MBlankQuestion;
@property(nonatomic,assign) int SurveyXMLElement_SChoiceQuestion;
@property(nonatomic,assign) int SurveyXMLElement_MChoiceQuestion;
@property(nonatomic,assign) int SurveyXMLElement_MChoiceOrderQuestion;
@property(nonatomic,assign) int SurveyXMLElement_ThreeBFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_MixMChoiceQuestion;
@property(nonatomic,assign) int SurveyXMLElement_BFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_SFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_MFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_SequenceQuestion;
@property(nonatomic,assign) int SurveyXMLElement_ThreeSFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_ThreeMFormQuestion;
@property(nonatomic,assign) int SurveyXMLElement_QuestionExpression;
@property(nonatomic,assign) int SurveyXMLElement_InitExpression;
@property(nonatomic,assign) int SurveyXMLElement_CheckExpression;
@property(nonatomic,assign) int SurveyXMLElement_OperateExpression;
@property(nonatomic,assign) int SurveyXMLElement_GotoExpression;
@property(nonatomic,assign) int SurveyXMLElement_ComputeBeforeValidExpression;
@property(nonatomic,assign) int SurveyXMLElement_PlaybackId;
@property(nonatomic,assign) int SurveyXMLElement_QuestionHead;
@property(nonatomic,assign) int SurveyXMLElement_QItem;
@property(nonatomic,assign) int SurveyXMLElement_QItemMedia;
@property(nonatomic,assign) int SurveyXMLElement_QItemPhoto;
@property(nonatomic,assign) int SurveyXMLElement_QItemMediaRecord;
@property(nonatomic,assign) int SurveyXMLElement_AItem;
@property(nonatomic,assign) int SurveyXMLElement_AItemMedia;
@property(nonatomic,assign) int SurveyXMLElement_CItem;
@property(nonatomic,assign) int SurveyXMLElement_CItemMedia;
@property(nonatomic,assign) int SurveyXMLElement_QuestionMedia;
@property(nonatomic,assign) int SurveyXMLElement_QuestionFileMedia;
@property(nonatomic,assign) int SurveyXMLElement_QuestionBackgroundMedia;
@property(nonatomic,assign) int SurveyXMLElement_QuestionPhoto;
@property(nonatomic,assign) int SurveyXMLElement_QuestionMediaRecord;
@property(nonatomic,assign) int SurveyXMLElement_QuestionMapMedia;
@property(nonatomic,assign) int SurveyXMLElement_MapNode;

@property(strong,nonatomic) NSArray* MapSurveyXMLAttrib;
@property(nonatomic,assign) int SurveyXMLAttrib_Id;
@property(nonatomic,assign) int SurveyXMLAttrib_Identity;
@property(nonatomic,assign) int SurveyXMLAttrib_SurveyName;
@property(nonatomic,assign) int SurveyXMLAttrib_SurveyCode;
@property(nonatomic,assign) int SurveyXMLAttrib_Creator;
@property(nonatomic,assign) int SurveyXMLAttrib_Modifier;
@property(nonatomic,assign) int SurveyXMLAttrib_CreateDate;
@property(nonatomic,assign) int SurveyXMLAttrib_ModifyDate;
@property(nonatomic,assign) int SurveyXMLAttrib_Status;
@property(nonatomic,assign) int SurveyXMLAttrib_Memo;
@property(nonatomic,assign) int SurveyXMLAttrib_NeedRecord;
@property(nonatomic,assign) int SurveyXMLAttrib_DenyEmptyAnswer;
@property(nonatomic,assign) int SurveyXMLAttrib_ChoiceDefaultCols;
@property(nonatomic,assign) int SurveyXMLAttrib_ShowPercentRule;
@property(nonatomic,assign) int SurveyXMLAttrib_HideWelcomeSentence;
@property(nonatomic,assign) int SurveyXMLAttrib_HidePrevButton;
@property(nonatomic,assign) int SurveyXMLAttrib_QuestionNoShowMode;
@property(nonatomic,assign) int SurveyXMLAttrib_ItemNoShowMode;
@property(nonatomic,assign) int SurveyXMLAttrib_SubSurveyAlternation;
@property(nonatomic,assign) int SurveyXMLAttrib_SubSurveyDraw;
@property(nonatomic,assign) int SurveyXMLAttrib_TitleFontFamily;
@property(nonatomic,assign) int SurveyXMLAttrib_TitleFontSize;
@property(nonatomic,assign) int SurveyXMLAttrib_TitleFontStyle;
@property(nonatomic,assign) int SurveyXMLAttrib_TipFontFamily;
@property(nonatomic,assign) int SurveyXMLAttrib_TipFontSize;
@property(nonatomic,assign) int SurveyXMLAttrib_TipFontStyle;
@property(nonatomic,assign) int SurveyXMLAttrib_ItemFontFamily;
@property(nonatomic,assign) int SurveyXMLAttrib_ItemFontSize;
@property(nonatomic,assign) int SurveyXMLAttrib_ItemFontStyle;
@property(nonatomic,assign) int SurveyXMLAttrib_WelcomeFontFamily;
@property(nonatomic,assign) int SurveyXMLAttrib_WelcomeFontSize;
@property(nonatomic,assign) int SurveyXMLAttrib_WelcomeFontStyle;
@property(nonatomic,assign) int SurveyXMLAttrib_QuitFontFamily;
@property(nonatomic,assign) int SurveyXMLAttrib_QuitFontSize;
@property(nonatomic,assign) int SurveyXMLAttrib_QuitFontStyle;
@property(nonatomic,assign) int SurveyXMLAttrib_DefaultTitleForeColor;
@property(nonatomic,assign) int SurveyXMLAttrib_DefaultTipForeColor;
@property(nonatomic,assign) int SurveyXMLAttrib_DefaultItemForeColor;
@property(nonatomic,assign) int SurveyXMLAttrib_WelcomeColor;
@property(nonatomic,assign) int SurveyXMLAttrib_QuitColor;
@property(nonatomic,assign) int SurveyXMLAttrib_SurveyGpsPolicy;
@property(nonatomic,assign) int SurveyXMLAttrib_Version;

@property(strong,nonatomic) NSArray* MapSubSurveyXMLAttrib;
@property(nonatomic,assign) int SubSurveyXMLAttrib_Id;
@property(nonatomic,assign) int SubSurveyXMLAttrib_Identity;
@property(nonatomic,assign) int SubSurveyXMLAttrib_Name;
@property(nonatomic,assign) int SubSurveyXMLAttrib_IsAlternation;
@property(nonatomic,assign) int SubSurveyXMLAttrib_IsDraw;
@property(nonatomic,assign) int SubSurveyXMLAttrib_Memo;
@property(nonatomic,assign) int SubSurveyXMLAttrib_IsSamePage;
@property(nonatomic,assign) int SubSurveyXMLAttrib_SectionAlternation;
@property(nonatomic,assign) int SubSurveyXMLAttrib_SectionDraw;

@property(strong,nonatomic) NSArray* MapSectionXMLAttrib;
@property(nonatomic,assign) int SectionXMLAttrib_Id;
@property(nonatomic,assign) int SectionXMLAttrib_Identity;
@property(nonatomic,assign) int SectionXMLAttrib_Name;
@property(nonatomic,assign) int SectionXMLAttrib_IsAlternation;
@property(nonatomic,assign) int SectionXMLAttrib_IsDraw;
@property(nonatomic,assign) int SectionXMLAttrib_Memo;
@property(nonatomic,assign) int SectionXMLAttrib_IsSamePage;
@property(nonatomic,assign) int SectionXMLAttrib_QuestionAlternation;
@property(nonatomic,assign) int SectionXMLAttrib_QuestionDraw;

@property(strong,nonatomic) NSArray* MapQuestionXMLAttrib;
@property(nonatomic,assign) int QuestionXMLAttrib_Id;
@property(nonatomic,assign) int QuestionXMLAttrib_Identity;
@property(nonatomic,assign) int QuestionXMLAttrib_Title;
@property(nonatomic,assign) int QuestionXMLAttrib_Code;
@property(nonatomic,assign) int QuestionXMLAttrib_Tip;
@property(nonatomic,assign) int QuestionXMLAttrib_IsAlternation;
@property(nonatomic,assign) int QuestionXMLAttrib_IsDraw;
@property(nonatomic,assign) int QuestionXMLAttrib_Memo;
@property(nonatomic,assign) int QuestionXMLAttrib_IsSamePage;
@property(nonatomic,assign) int QuestionXMLAttrib_IsDumb;
@property(nonatomic,assign) int QuestionXMLAttrib_IsQuota;
@property(nonatomic,assign) int QuestionXMLAttrib_QuotaFailedExpression;
@property(nonatomic,assign) int QuestionXMLAttrib_FontFamily;
@property(nonatomic,assign) int QuestionXMLAttrib_FontSize;
@property(nonatomic,assign) int QuestionXMLAttrib_FontStyle;
@property(nonatomic,assign) int QuestionXMLAttrib_ForeColor;
@property(nonatomic,assign) int QuestionXMLAttrib_TipFontFamily;
@property(nonatomic,assign) int QuestionXMLAttrib_TipFontSize;
@property(nonatomic,assign) int QuestionXMLAttrib_TipFontStyle;
@property(nonatomic,assign) int QuestionXMLAttrib_TipForeColor;
@property(nonatomic,assign) int QuestionXMLAttrib_Style;
@property(nonatomic,assign) int QuestionXMLAttrib_MinItemAnswer;
@property(nonatomic,assign) int QuestionXMLAttrib_MaxItemAnswer;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemAlternation;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemDraw;
@property(nonatomic,assign) int QuestionXMLAttrib_OptionListId;
@property(nonatomic,assign) int QuestionXMLAttrib_CategoryListId;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemLayout;
@property(nonatomic,assign) int QuestionXMLAttrib_TableOddRowBColorSet;
@property(nonatomic,assign) int QuestionXMLAttrib_TableEvenRowBColorSet;
@property(nonatomic,assign) int QuestionXMLAttrib_TableOddColBColorSet;
@property(nonatomic,assign) int QuestionXMLAttrib_TableEvenColBColorSet;
@property(nonatomic,assign) int QuestionXMLAttrib_TableOddRowBColor;
@property(nonatomic,assign) int QuestionXMLAttrib_TableEvenRowBColor;
@property(nonatomic,assign) int QuestionXMLAttrib_TableOddColBColor;
@property(nonatomic,assign) int QuestionXMLAttrib_TableEvenColBColor;
@property(nonatomic,assign) int QuestionXMLAttrib_AItemAlternation;
@property(nonatomic,assign) int QuestionXMLAttrib_CItemAlternation;
@property(nonatomic,assign) int QuestionXMLAttrib_CItemDraw;
@property(nonatomic,assign) int QuestionXMLAttrib_AnswerTimeLimitMode;
@property(nonatomic,assign) int QuestionXMLAttrib_AnswerTimeLimit;
@property(nonatomic,assign) int QuestionXMLAttrib_NeedRecord;
@property(nonatomic,assign) int QuestionXMLAttrib_IgnoreLastAnswer;
@property(nonatomic,assign) int QuestionXMLAttrib_DenyEmptyAnswer;
@property(nonatomic,assign) int QuestionXMLAttrib_CanSkip;
@property(nonatomic,assign) int QuestionXMLAttrib_CItemIndexHide;
@property(nonatomic,assign) int QuestionXMLAttrib_QItemIndexHide;
@property(nonatomic,assign) int QuestionXMLAttrib_AItemIndexHide;
@property(nonatomic,assign) int QuestionXMLAttrib_OptionDisplayOrder;
@property(nonatomic,assign) int QuestionXMLAttrib_OptionDisplayStyle;
@property(nonatomic,assign) int QuestionXMLAttrib_ScaleStyle;
@property(nonatomic,assign) int QuestionXMLAttrib_MinScaleText;
@property(nonatomic,assign) int QuestionXMLAttrib_MaxScaleText;
@property(nonatomic,assign) int QuestionXMLAttrib_CItemImageStyleSetting;
@property(nonatomic,assign) int QuestionXMLAttrib_QItemImageStyleSetting;
@property(nonatomic,assign) int QuestionXMLAttrib_AItemImageStyleSetting;
@property(nonatomic,assign) int QuestionXMLAttrib_QuestionShowItemNo;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemColNums;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemColWidth;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemColSpace;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemRowSpace;
@property(nonatomic,assign) int QuestionXMLAttrib_ShowItemTitleInRule;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMarginLeft;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMarginRight;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMarginTop;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMarginBottom;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadSpaceBetweenTitleTip;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadSpaceBetweenTitleMedia;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMediaTitlePos;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadTitleTipPos;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadTitleAlign;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadTipAlign;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadMediaAlign;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadTitleWidth;
@property(nonatomic,assign) int QuestionXMLAttrib_QHeadTipWidth;
@property(nonatomic,assign) int QuestionXMLAttrib_TableRowWidth;
@property(nonatomic,assign) int QuestionXMLAttrib_TableCItemRowWidth;
@property(nonatomic,assign) int QuestionXMLAttrib_QuestionPhotoPolicy;
@property(nonatomic,assign) int QuestionXMLAttrib_QuestionMediaRecordPolicy;
@property(nonatomic,assign) int QuestionXMLAttrib_GpsPolicy;
@property(nonatomic,assign) int QuestionXMLAttrib_TitleHasScript;
@property(nonatomic,assign) int QuestionXMLAttrib_TipHasScript;
@property(nonatomic,assign) int QuestionXMLAttrib_ItemTitleHasScript;

@property(strong,nonatomic) NSArray* MapItemXMLAttrib;
@property(nonatomic,assign) int ItemXMLAttrib_Id;
@property(nonatomic,assign) int ItemXMLAttrib_Identity;
@property(nonatomic,assign) int ItemXMLAttrib_Title;
@property(nonatomic,assign) int ItemXMLAttrib_Code;
@property(nonatomic,assign) int ItemXMLAttrib_Category;
@property(nonatomic,assign) int ItemXMLAttrib_Index;
@property(nonatomic,assign) int ItemXMLAttrib_IsAlternation;
@property(nonatomic,assign) int ItemXMLAttrib_IsDraw;
@property(nonatomic,assign) int ItemXMLAttrib_IsOpen;
@property(nonatomic,assign) int ItemXMLAttrib_IsHold;
@property(nonatomic,assign) int ItemXMLAttrib_Prop;
@property(nonatomic,assign) int ItemXMLAttrib_Min;
@property(nonatomic,assign) int ItemXMLAttrib_Max;
@property(nonatomic,assign) int ItemXMLAttrib_MaxNumOperator;
@property(nonatomic,assign) int ItemXMLAttrib_MinNumOperator;
@property(nonatomic,assign) int ItemXMLAttrib_OpenTextShowAsPwd;
@property(nonatomic,assign) int ItemXMLAttrib_Memo;
@property(nonatomic,assign) int ItemXMLAttrib_FontFamily;
@property(nonatomic,assign) int ItemXMLAttrib_FontSize;
@property(nonatomic,assign) int ItemXMLAttrib_FontStyle;
@property(nonatomic,assign) int ItemXMLAttrib_ForeColor;
@property(nonatomic,assign) int ItemXMLAttrib_OptionListItemId;
@property(nonatomic,assign) int ItemXMLAttrib_CategoryListItemId;
@property(nonatomic,assign) int ItemXMLAttrib_WithKnowledge;
@property(nonatomic,assign) int ItemXMLAttrib_ImageTextShowMode;
@property(nonatomic,assign) int ItemXMLAttrib_ImageTextPos;
@property(nonatomic,assign) int ItemXMLAttrib_MarkEndTime;
@property(nonatomic,assign) int ItemXMLAttrib_IsOpenTextShowByDigit;
@property(nonatomic,assign) int ItemXMLAttrib_OpenTextFractionNum;
@property(nonatomic,assign) int ItemXMLAttrib_OpenTextPrefix;
@property(nonatomic,assign) int ItemXMLAttrib_OpenTextPostfix;
@property(nonatomic,assign) int ItemXMLAttrib_ItemColWidth;
@property(nonatomic,assign) int ItemXMLAttrib_TitleHasScript;

@property(strong,nonatomic) NSArray* MapMediaXMLAttrib;
@property(nonatomic,assign) int MediaXMLAttrib_Id;
@property(nonatomic,assign) int MediaXMLAttrib_Title;
@property(nonatomic,assign) int MediaXMLAttrib_Index;
@property(nonatomic,assign) int MediaXMLAttrib_MediaCategory;
@property(nonatomic,assign) int MediaXMLAttrib_MediaFormat;
@property(nonatomic,assign) int MediaXMLAttrib_SizeMode;
@property(nonatomic,assign) int MediaXMLAttrib_Width;
@property(nonatomic,assign) int MediaXMLAttrib_Height;
@property(nonatomic,assign) int MediaXMLAttrib_DisplayMode;
@property(nonatomic,assign) int MediaXMLAttrib_FilePath;
@property(nonatomic,assign) int MediaXMLAttrib_WebFilePath;
@property(nonatomic,assign) int MediaXMLAttrib_Memo;
@property(nonatomic,assign) int MediaXMLAttrib_FillColor;

@property(strong,nonatomic) NSArray* MapMapNodeXMLAttrib;
@property(nonatomic,assign) int MapNodeXMLAttrib_Id;
@property(nonatomic,assign) int MapNodeXMLAttrib_Index;
@property(nonatomic,assign) int MapNodeXMLAttrib_ItemId;
@property(nonatomic,assign) int MapNodeXMLAttrib_ShapeType;
@property(nonatomic,assign) int MapNodeXMLAttrib_PointStr;
@property(nonatomic,assign) int MapNodeXMLAttrib_Title;

@property(strong,nonatomic) NSArray* MapSentenceXMLAttrib;
@property(nonatomic,assign) int MapSentenceXMLAttrib_Id;
@property(nonatomic,assign) int MapSentenceXMLAttrib_Identity;
@property(nonatomic,assign) int MapSentenceXMLAttrib_Title;
@property(nonatomic,assign) int MapSentenceXMLAttrib_Expression;

//问卷变量
@property(strong,nonatomic)NSArray* MapVariablesXMLAttrib;
@property(nonatomic,assign)int MapVariablesXMLAttrib_Id;
@property(nonatomic,assign)int MapVariablesXMLAttrib_Name;
@property(nonatomic,assign)int MapVariablesXMLAttrib_Type;

//选项列表
@property(strong,nonatomic)NSArray* MapListsXMLAttrib;
@property(nonatomic,assign)int MapListsXMLAttrib_Id;
@property(nonatomic,assign)int MapListsXMLAttrib_Index;
@property(nonatomic,assign)int MapListsXMLAttrib_Name;
@end